# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:Mikolaj Roszak www.mikolaj.com
Adres odbiorcy: Przedwiośnie, 79/12, 73-110, Stargard, PL
Tel. +48 500 487 977
Skype: mikolajroszak_1
Zoom: Mikołaj Roszak
email: ul.echo12@gmail.com
REGON: 383183972
NIP: 854-156-08-32
Finanse
Dane konta Revolut
IBAN: LT41 3250 0894 7676 6825
BIC: REVOLT21
Konto (tylko przelewy krajowe): 2029 1000 0600 0000 0003 1339 92

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
